### ISSUE TITLE
Handle/truncate too-large JSON data without erroring

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench#394]
## What happened just before the problem occurred

Several issues, #392, #391 and maybe https://twitter.com/dlderod/status/938587178204098562?s=09, are seeing an issue because the JSON string for a really large image is too big to store in the database. 

## Relevant URLs

Example: https://spectralworkbench.org/spectrums/120774

3263 pixels wide - that's **179545 characters**

The error we see is:

```ruby
Completed 500 Internal Server Error in 58.6ms

MultiJson::ParseError (399: unexpected token at '{"average":7.65,"r":7.65,"g":2'):
  app/models/spectrum.rb:512:in `latest_json_data'
  app/models/spectrum.rb:521:in `generate_hashed_values'
  app/models/spectrum.rb:504:in `generate_processed_spectrum'
  app/models/tag.rb:68:in `scan_powertags_after_save'
  app/controllers/tags_controller.rb:32:in `create'
```

That's on this line:

https://github.com/publiclab/spectral-workbench/blob/master/app/models/spectrum.rb#L512

```ruby
      return ActiveSupport::JSON.decode(self.snapshots.last.data)
```

So, what are our options? 

1. make the database column bigger
2. safely truncate or down-res the data before storing
3. anything else?

I'm going to start with a test.

**Comment by jywarren** [comment]
I think we could increase the storage size, but that might dramatically affect performance. I also doubt that we need 3200 pixels of resolution... at least not yet. 

https://stackoverflow.com/questions/9670834/rails-change-column-to-mediumtext#19389681

**Comment by jywarren** [comment]
Actually `spectrums` is already that long: `t.text     "data",                  :limit => 4294967295`

Let's just do this.

**Comment by jywarren** [comment]
Working in #395
